/**
 * @type {import('next-sitemap').IConfig}
 *
 * ⚠️ DEPRECATED: Sitemap is now generated dynamically via app/sitemap.ts
 * This config is kept for reference only. Do NOT run `next-sitemap` manually.
 * The static files in public/ (sitemap.xml, sitemap-0.xml) are legacy artifacts.
 */
module.exports = {
  siteUrl: 'https://www.honeywellhydraulics.com',
  generateRobotsTxt: false,
  generateIndexSitemap: false, // Disabled — using app/sitemap.ts instead

  // ── Exclude non-indexable routes and non-page assets ──
  exclude: [
    '/thank-you',
    '/thank-you/*',
    '/admin',
    '/admin/*',
    '/api',
    '/api/*',
    '/search',
    '/search/*',
    '/apple-icon.png',
    '/icon.png',
    '/robots.txt',
  ],

  // ── robots.txt policies ──
  // NOTE: robots.txt is generated by app/robots.ts, NOT this config.
  // These policies are kept here for reference only and MUST match robots.ts.
  robotsTxtOptions: {
    policies: [
      // Search engine crawlers
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/search', '/admin/', '/api/', '/thank-you/'],
      },
      // Google
      { userAgent: 'Googlebot', allow: '/', },
      { userAgent: 'Googlebot-Image', allow: '/', },
      // Bing
      { userAgent: 'Bingbot', allow: '/', },
      // AI crawlers — BLOCKED until site build is complete (matches robots.ts)
      { userAgent: 'GPTBot', disallow: '/', },
      { userAgent: 'Google-Extended', disallow: '/', },
      { userAgent: 'ClaudeBot', disallow: '/', },
      { userAgent: 'PerplexityBot', disallow: '/', },
      // Block scraper bots
      { userAgent: 'AhrefsBot', disallow: '/', },
      { userAgent: 'SemrushBot', disallow: '/', },
      { userAgent: 'MJ12bot', disallow: '/', },
      { userAgent: 'DotBot', disallow: '/', },
    ],
  },

  // ── Per-path priority and changefreq overrides ──
  transform: async (config, path) => {
    // Homepage
    if (path === '/') {
      return { loc: path, changefreq: 'weekly', priority: 1.0, lastmod: new Date().toISOString() };
    }

    // Products hub
    if (path === '/products' || path === '/products/') {
      return { loc: path, changefreq: 'weekly', priority: 0.9, lastmod: new Date().toISOString() };
    }

    // Product pillar pages
    const productPillars = [
      '/products/hydraulic-cylinders',
      '/products/hydraulic-power-packs',
      '/products/manifold-blocks',
      '/products/hydraulic-accessories',
    ];
    if (productPillars.some((p) => path === p || path === `${p}/`)) {
      return { loc: path, changefreq: 'weekly', priority: 0.9, lastmod: new Date().toISOString() };
    }

    // Request quote
    if (path.startsWith('/request-quote')) {
      return { loc: path, changefreq: 'monthly', priority: 0.9, lastmod: new Date().toISOString() };
    }

    // Key location pages
    const keyLocations = ['/locations/ahmedabad', '/locations/gujarat', '/locations/india'];
    if (keyLocations.some((l) => path.startsWith(l))) {
      return { loc: path, changefreq: 'monthly', priority: 0.9, lastmod: new Date().toISOString() };
    }

    // Individual product pages (children of pillars)
    if (productPillars.some((p) => path.startsWith(p + '/') && path !== p && path !== `${p}/`)) {
      return { loc: path, changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() };
    }

    // Industry pages
    if (path.startsWith('/industries/')) {
      return { loc: path, changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() };
    }

    // Blog articles
    if (path.startsWith('/blog/')) {
      return { loc: path, changefreq: 'monthly', priority: 0.7, lastmod: new Date().toISOString() };
    }

    // Other location pages
    if (path.startsWith('/locations/')) {
      return { loc: path, changefreq: 'monthly', priority: 0.7, lastmod: new Date().toISOString() };
    }

    // Company Pages
    const companyPages = [
      '/about-us',
      '/infrastructure',
      '/quality',
      '/manufacturing-facility',
      '/contact-us'
    ];
    if (companyPages.some((p) => path === p)) {
      return { loc: path, changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() };
    }

    // Case studies
    if (path.startsWith('/case-studies/')) {
      return { loc: path, changefreq: 'monthly', priority: 0.6, lastmod: new Date().toISOString() };
    }

    // Resources (FAQ, Downloads)
    if (path.startsWith('/resources/')) {
      return { loc: path, changefreq: 'monthly', priority: 0.6, lastmod: new Date().toISOString() };
    }

    // Legal pages
    if (path.startsWith('/privacy') || path.startsWith('/terms')) {
      return { loc: path, changefreq: 'yearly', priority: 0.2, lastmod: new Date().toISOString() };
    }

    // Default fallback
    return {
      loc: path,
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.lastmod ? new Date().toISOString() : undefined,
    };
  },
};
