import React from 'react';
import {
  Zap,
  Box,
  Thermometer,
  Truck,
  CheckCircle2,
  Activity
} from 'lucide-react';

import type { FAQ, PowerPackSpec, PowerPackFeature, PowerPackIndustry } from './types';

export const DC_MINI_FAQS: FAQ[] = [
  {
    question: 'Can a 12V DC power pack lift a heavy dump truck?',
    answer: 'Yes. The hydraulic pressure (which dictates the lifting force) is generated by the pump, not the voltage. A 12V motor can easily spin a small pump to generate 3000 PSI, which is enough to lift a massive load. The 12V system will simply draw more amperage from the battery than a 24V system to do the same work.',
  },
  {
    question: 'Why does my DC power pack motor get so hot?',
    answer: 'DC motors do not have internal cooling fans like AC motors, and they draw massive electrical amperage. They are designed for short bursts of work (intermittent duty). If you run the motor continuously for several minutes, it will overheat and eventually burn out the internal windings.',
  },
  {
    question: 'Can I use a DC power pack for a factory conveyor belt?',
    answer: 'No. A factory conveyor requires continuous, 24/7 rotational power. A DC power pack will burn out within minutes. For continuous indoor factory applications, you must use a 3-Phase Hydraulic Power Pack.',
  },
  {
    question: 'Do you manufacture the central manifolds for the DC units?',
    answer: 'Yes. We CNC-machine the central aluminum logic blocks in-house. This allows us to create ultra-compact units with perfectly integrated directional and relief valving, eliminating external pipes and leaks.',
  },
];

export const DC_MINI_SPECS: PowerPackSpec[] = [
  { parameter: 'Electric Motor Inputs', value: '12V DC or 24V DC' },
  { parameter: 'Motor Power Ratings', value: '0.5 kW to 3.0 kW (Standard up to 4.5 HP)' },
  { parameter: 'Pump Architecture', value: 'High-efficiency micro gear pumps' },
  { parameter: 'Maximum Operating Pressure', value: 'Up to 250 Bar (3600 PSI)' },
  { parameter: 'Reservoir Capacity', value: '2 Liters to 25 Liters (Cylindrical or Square, Steel or Translucent Plastic)' },
  { parameter: 'Mounting Orientation', value: 'Horizontal or Vertical Mounting' },
  { parameter: 'Control Logic', value: '2/2, 3/2, or 4/3 solenoid directional valves integrated into central block' },
  { parameter: 'Duty Cycle', value: 'Strictly Intermittent (S2 / S3 ratings)' },
];

export const DC_MINI_FEATURES: PowerPackFeature[] = [
  {
    icon: <Zap className="w-6 h-6" />,
    title: 'A. Battery Power & DC Motors',
    description: 'The prime mover is a 12V or 24V DC electric motor wired directly to the vehicle\'s battery or alternator system. These motors are designed for high starting torque to immediately force hydraulic fluid through the system under full load. However, because they draw immense amperage from the battery, they are strictly rated for intermittent duty.',
  },
  {
    icon: <Box className="w-6 h-6" />,
    title: 'B. Integrated Central Manifolds',
    description: 'To save space, there are almost no external pipes or hoses. The fluid logic is entirely integrated into a central aluminum or steel block. The pump is submerged inside the tank, pulling fluid and pushing it directly into the manifold\'s internal CNC-drilled galleries, where it is routed to the lifting cylinders by integrated solenoid valves.',
  },
  {
    icon: <Thermometer className="w-6 h-6" />,
    title: 'C. Compact Reservoirs',
    description: 'Because DC units operate intermittently, the hydraulic fluid does not have time to reach boiling temperatures. Therefore, massive steel heat-sink tanks are unnecessary. We utilize highly compact, cylindrical steel or translucent plastic reservoirs (typically 2 to 15 liters), which perfectly fit under truck chassis or inside small control cabinets.',
  },
];

export const DC_MINI_INDUSTRIES: PowerPackIndustry[] = [
  {
    icon: <Truck className="w-6 h-6" />,
    industryName: 'Transportation & Commercial Vehicles',
    description: 'Supplying ultra-reliable power units for massive fleets of commercial delivery trucks and heavy haulers.',
    href: '#'
  },
  {
    icon: <Box className="w-6 h-6" />,
    industryName: 'Material Handling & Logistics',
    description: 'Designing highly compact 24V units for electric pallet jacks, stackers, and mobile elevating work platforms.',
    href: '#'
  },
  {
    icon: <CheckCircle2 className="w-6 h-6" />,
    industryName: 'Municipal Equipment',
    description: 'Delivering weather-resistant power packs for garbage trucks, street sweepers, and snowplows operating far from grids.',
    href: '#'
  },
  {
    icon: <Activity className="w-6 h-6" />,
    industryName: 'Mobile Agricultural Machinery',
    description: 'Providing battery-operated actuation for remote farm implements and trailer lifts.',
    href: '#'
  },
];
