import React from 'react';
import { ShieldCheck, ArrowUpToLine, Settings, ShieldAlert, HardHat, Scale, Cog, FlaskConical, Package } from 'lucide-react';
import { FaIndustry, FaBuilding, FaWarehouse, FaCarSide } from 'react-icons/fa';
import type { ProductPageData } from '@/components/product-page/types';

export const carParkingCylinderData: ProductPageData = {
  // ── SEO ──
  seo: {
    title: 'Car Parking Hydraulic Cylinder Manufacturer | Honeywell Hydraulics',
    description: 'Heavy-duty hydraulic cylinder for car parking systems and vehicle lifts. Engineered for smooth vertical lifting with high load capacity (Up to 3000 kg).',
    url: '/products/hydraulic-cylinders/car-parking-hydraulic-cylinders',
    image: '/images/products/hydraulic-cylinders/car-parking-hydraulic-cylinder-v2.webp',
  },

  // ── Schema ──
  schema: {
    productName: 'Car Parking Hydraulic Cylinder',
    category: 'Hydraulic Cylinders',
    properties: [
      { name: 'Lifting Capacity', value: 'Up to 3000 kg' },
      { name: 'Lifting Height', value: 'Up to 2100 mm' },
      { name: 'Working Pressure', value: 'Up to 250 Bar' },
      { name: 'Application', value: 'Stack Parking & Multi-Level Car Lifts' },
    ],
  },

  // ── Hero ──
  hero: {
    breadcrumbs: [
      { label: 'Home', href: '/' },
      { label: 'Products', href: '/products/' },
      { label: 'Hydraulic Cylinders', href: '/products/hydraulic-cylinders/' },
    ],
    currentPage: 'Car Parking Cylinders',
    subtitle: 'Smooth & Stable Vehicle Lifting',
    h1: 'Car Parking Hydraulic Cylinder Manufacturer',
    description: 'Honeywell Hydraulics manufactures premium hydraulic cylinders designed specifically for modern car parking systems. Engineered for high-cycle continuous operation, our cylinders provide the reliable, judder-free lifting force required to safely raise and lower vehicles in stack parking, multi-level systems, and automated parking structures.',
    primaryCta: { label: 'REQUEST A QUOTE', href: '/request-quote/#quote-form' },
    secondaryCta: { label: 'TECHNICAL SPECS', href: '#technical-specifications' },
    image: {
      src: '/images/products/hydraulic-cylinders/car-parking-hydraulic-cylinder-v2.webp',
      alt: 'Heavy duty car parking hydraulic cylinder manufactured in Ahmedabad, Gujarat',
    },
    keySpecs: [
      { label: 'Capacity', value: 'Up to 3000 kg' },
      { label: 'Lifting Height', value: 'Up to 2100mm' },
      { label: 'Protection', value: 'Overload Valves' },
      { label: 'Durability', value: 'High Cycle Life' },
    ],
  },

  // ── Overview ──
  overview: {
    heading: 'Engineered for Automated & Stack Parking Systems',
    content: (
      <>
        <p>
          Hydraulic cylinders are the critical muscle behind <strong className="text-honeywell-navy">Car Parking Hydraulic Systems</strong>. Mounted vertically within the lift structure, these mechanical actuators convert hydraulic fluid pressure into the precise linear force and motion necessary to lift vehicles in and out of elevated parking spaces. 
        </p>
        <p>
          Unlike standard industrial cylinders, car parking cylinders must operate with absolute stability to ensure passenger safety and prevent vehicle damage. At Honeywell Hydraulics, we manufacture cylinders with advanced H8 tolerance honed tubes and premium polyurethane seals that guarantee a smooth, controlled ascent and descent, completely eliminating the &quot;stick-slip&quot; juddering effect.
        </p>
        <p>
          Our cylinders are highly cost-effective and built to withstand the rigors of continuous, high-cycle use in both indoor basement parking lots and exposed outdoor parking structures. They feature integrated safety mechanisms, including pressure relief valves and overload protection, making them the most reliable choice for OEM parking system manufacturers.
        </p>
      </>
    ),
  },

  // ── Key Features ──
  keyFeatures: {
    heading: 'Core Advantages & Safety Features',
    description: 'Our car parking cylinders are precision-engineered to handle heavy vehicle loads while maintaining absolute safety and smooth operation.',
    showStepNumbers: false,
    items: [
      {
        icon: <ArrowUpToLine className="w-6 h-6" />,
        title: 'Smooth & Stable Lifting',
        description: 'Provides precise control over the lifting process, allowing vehicles to be lifted or lowered at a controlled, judder-free speed for maximum safety.',
      },
      {
        icon: <Scale className="w-6 h-6" />,
        title: 'Efficient Power Transmission',
        description: 'Converts the pressure generated by the hydraulic pump into linear force with minimal energy loss, perfect for lifting heavy 3000 kg vehicle loads.',
      },
      {
        icon: <ShieldCheck className="w-6 h-6" />,
        title: 'Integrated Safety Systems',
        description: 'Designed with overload protection and pressure relief valves to prevent system damage and ensure safe operation during power failures or pressure spikes.',
      },
      {
        icon: <Settings className="w-6 h-6" />,
        title: 'Extreme Versatility',
        description: 'Available in vertical or horizontal mounting, single or multi-stage telescopic designs, and with customized piston rod sizes and stroke lengths.',
      },
      {
        icon: <ShieldAlert className="w-6 h-6" />,
        title: 'Shock & Vibration Resistant',
        description: 'Engineered to absorb the dynamic shocks and eccentric vibrations frequently encountered in busy, high-throughput commercial parking environments.',
      },
      {
        icon: <HardHat className="w-6 h-6" />,
        title: 'Weather & Corrosion Proof',
        description: 'Manufactured with hard-chrome plated rods and weather-resistant seal kits to operate flawlessly in both indoor basement and exposed outdoor parking systems.',
      },
    ],
  },

  // ── Technical Specs ──
  technicalSpecs: {
    heading: 'Technical Specifications',
    description: 'Our car parking cylinders are manufactured using the finest quality materials to meet the rigorous demands of vehicle lifting and storage.',
    primaryCta: { label: 'DISCUSS YOUR PARKING LIFT', href: '/request-quote/#quote-form' },
    secondaryCta: { label: 'VIEW ALL PRODUCTS', href: '/products/hydraulic-cylinders/' },
    tableTitle: 'Car Parking Cylinder Specs',
    rows: [
      { parameter: 'Maximum Lifting Height (Stroke)', value: 'Up to 2100 mm (Standard)' },
      { parameter: 'Maximum Load Capacity', value: 'Up to 3000 kg (3 Ton)' },
      { parameter: 'Working Pressure', value: 'Up to 250 Bar' },
      { parameter: 'Tube Material', value: 'ST52 Seamless Honed Tube (H8 Tolerance)' },
      { parameter: 'Piston Rod Material', value: 'EN8 / C45, Hard Chrome Plated (HCP)' },
      { parameter: 'Mounting Options', value: 'Trunnion, Flange, Clevis, or Custom OEM Mounts' },
      { parameter: 'Seal Kits', value: 'Polyurethane seals (Parker / Hallite equivalent)' },
      { parameter: 'Safety Integration', value: 'Port for Rupture Valves / Velocity Fuses' },
    ],
  },

  // ── Variants ──
  variants: {
    heading: 'Cylinder Configurations for Parking Systems',
    description: 'Depending on the architectural constraints of the building and the type of parking system, we manufacture different structural configurations.',
    items: [
      {
        icon: <ArrowUpToLine className="w-7 h-7" />,
        title: 'Single-Acting Displacement Cylinders',
        description: 'The standard choice for most 2-post and 4-post stack parking lifts. Hydraulic pressure extends the rod to lift the vehicle, while the weight of the platform (gravity) safely retracts the cylinder.',
        highlights: [
          'Gravity-return operation',
          'Highly cost-effective',
          'Fewer wear seals required',
        ],
      },
      {
        icon: <Settings className="w-7 h-7" />,
        title: 'Telescopic Parking Cylinders',
        description: 'Ideal for multi-level parking or basement systems with limited pit depth. Telescopic cylinders provide a long stroke (lifting height) from a highly compact retracted length.',
        highlights: [
          'Multi-stage extension',
          'Perfect for shallow pits',
          'Saves structural space',
        ],
      },
      {
        icon: <Scale className="w-7 h-7" />,
        title: 'Synchronized Dual Cylinders',
        description: 'For wide platform car elevators or heavy SUV parking systems. We engineer identical pairs of cylinders designed to operate in perfect unison using specialized flow dividers to prevent platform tilting.',
        highlights: [
          'Prevents vehicle tilting',
          'Handles off-center loads',
          'Distributes mechanical stress',
        ],
      },
    ],
  },

  // ── Comparisons ──
  comparisons: [
    {
      heading: 'Car Parking Lifts vs. Standard Industrial Lifts',
      description: 'Why you cannot use a standard off-the-shelf cylinder for vehicle parking systems.',
      columns: [{ heading: 'Engineering Feature' }, { heading: 'Car Parking Cylinders' }, { heading: 'Standard Industrial Cylinders' }],
      rows: [
        { feature: 'Weather Sealing', values: [{ text: 'High (Wiper seals resist rain, snow, salt)', highlight: true }, { text: 'Low (Designed for indoor factory use)' }] },
        { feature: 'Rod Protection', values: [{ text: 'Heavy Hard-Chrome Plating (Anti-corrosion)' }, { text: 'Standard Chrome Plating' }] },
        { feature: 'Cycle Rate', values: [{ text: 'High frequency (Multiple cars per day)' }, { text: 'Variable depending on application' }] },
        { feature: 'Descent Control', values: [{ text: 'Integrated flow-control valves for smooth lowering' }, { text: 'External valving required' }] },
      ],
    }
  ],

  // ── Engineering / How to Choose ──
  engineering: {
    heading: 'Engineering Considerations for Parking Lifts',
    description: 'Vehicle lifts pose unique environmental and synchronization challenges.',
    items: [
      {
        label: 'A',
        title: 'Outdoor Weather Sealing',
        description: 'Parking stackers are frequently installed outdoors or in damp basements. We equip these cylinders with aggressive polyurethane wiper seals to scrape away ice, dirt, and road salt before it can penetrate the rod seal and contaminate the hydraulic fluid.',
      },
      {
        label: 'B',
        title: 'Cylinder Synchronization',
        description: 'For wide 4-post lifts handling heavy SUVs, the lift must remain perfectly level even if the vehicle\'s weight is off-center. We engineer identical paired cylinders optimized to run through a rotary flow divider to ensure absolute synchronous extension.',
      },
      {
        label: 'C',
        title: 'Mechanical Locking Interfaces',
        description: 'For long-term vehicle storage, the hydraulic cylinder should not hold the pressure indefinitely. We can design the cylinder mounting architecture to seamlessly interface with mechanical safety locks (pawls) that engage when the lift reaches its upper limit.',
      },
    ],
  },

  // ── Industries ──
  industries: {
    heading: 'Applications & Parking Systems',
    description: 'Our parking cylinders are trusted by OEMs and infrastructure developers across a wide range of vehicle storage solutions.',
    items: [
      {
        icon: <FaCarSide className="w-6 h-6" />,
        name: 'Stack Parking Systems',
        description: 'Standard 2-post and 4-post residential and commercial stack parking lifts to double parking capacity.',
        href: '#',
      },
      {
        icon: <FaBuilding className="w-6 h-6" />,
        name: 'Multi-Level Parking',
        description: 'Automated puzzle parking and tower parking systems for high-density urban commercial buildings.',
        href: '#',
      },
      {
        icon: <FaWarehouse className="w-6 h-6" />,
        name: 'Basement Parking',
        description: 'Compact pit-parking and subterranean vehicle lifts designed for limited overhead clearance.',
        href: '#',
      },
      {
        icon: <FaIndustry className="w-6 h-6" />,
        name: 'Car Elevators',
        description: 'Heavy-duty hydraulic vehicle elevators for moving cars between floors in showrooms and service centers.',
        href: '#',
      },
    ],
  },

  // ── Manufacturing ──
  manufacturing: {
    heading: 'OEM Manufacturing Excellence',
    description: 'We partner with leading parking system manufacturers to supply reliable, custom-engineered hydraulic cylinders in high volumes.',
    steps: [
      {
        icon: <Cog className="w-6 h-6" />,
        title: 'High-Volume CNC Turning',
        description: 'To meet the demanding volume requirements of parking lift OEMs, we utilize automated CNC turning centers to rapidly machine identical ST52 barrels and pistons with micron-level consistency.',
      },
      {
        icon: <FlaskConical className="w-6 h-6" />,
        title: 'Corrosion-Resistant Chrome Plating',
        description: 'Since parking cylinders face outdoor exposure, the EN8 piston rods undergo a heavy hard-chrome plating process (25+ microns) to strictly prevent pitting and rust from road salt and humidity.',
      },
      {
        icon: <ShieldAlert className="w-6 h-6" />,
        title: 'Automated Assembly',
        description: 'Cylinders are assembled in a clean environment to prevent any particulate contamination, utilizing specialized jigs to ensure the high-pressure rod seals are seated perfectly without tearing.',
      },
      {
        icon: <Package className="w-6 h-6" />,
        title: 'Batch Pressure Testing',
        description: 'Every single OEM production batch undergoes rigorous 1.5x hydrostatic testing and simulated cycle testing to ensure zero-leak performance and flawless descent speeds before bulk packaging.',
      },
    ],
    midCta: {
      heading: 'Need Cylinders for Your Parking Systems?',
      description: 'Our engineers can design and manufacture cylinders in volume based on your specific platform size and lifting height requirements.',
      primaryCta: { label: 'SUBMIT OEM REQUIREMENTS', href: '/request-quote/#quote-form' },
      whatsappLabel: 'WhatsApp Us',
    },
  },

  // ── Spotlights (Case Studies) ──
  spotlights: [
    {
      badge: 'CASE STUDY',
      heading: 'Providing High-Cycle Cylinders for a 200-Car Automated Puzzle Parking Facility',
      subheading: 'Commercial Complex — Mumbai, Maharashtra',
      stats: [
        { value: '3000', label: 'kg Capacity' },
        { value: '24/7', label: 'Continuous Operation' },
        { value: '100%', label: 'Safety Compliance' },
      ],
      phases: [
        {
          number: '01',
          title: 'The Challenge',
          description: "A parking system OEM required highly reliable hydraulic cylinders for a massive automated puzzle parking project in Mumbai. The cylinders needed to operate continuously in a high-humidity environment without seal degradation or rusting.",
        },
        {
          number: '02',
          title: 'The Engineering',
          description: "We manufactured custom single-acting displacement cylinders featuring heavy hard-chrome plated rods for superior corrosion resistance and high-grade polyurethane wiper seals to keep urban dust and moisture out of the hydraulic system.",
        },
        {
          number: '03',
          variant: 'dark',
          title: 'The Outcome',
          description: "The cylinders were successfully integrated into the 200-car facility, providing smooth, reliable lifting with zero reported leaks or downtime over three years of continuous high-cycle operation.",
          cta: { label: 'READ FULL CASE STUDY', href: '#' },
        },
      ],
    },
  ],

  // ── Related Products ──
  relatedProducts: {
    description: 'Explore our other hydraulic cylinders and power units designed for industrial material handling.',
    items: [
      {
        title: 'Goods Lift Hydraulic Cylinders',
        description: 'Heavy-duty cylinders with integrated safety rupture valves for industrial freight elevators.',
        category: 'Hydraulic Cylinders',
        imageSrc: '/images/products/hydraulic-cylinders/goods-lift-hydraulic-cylinder-v2.webp',
        href: '/products/hydraulic-cylinders/goods-lift-hydraulic-cylinders/',
        ctaText: 'View Details',
      },
      {
        title: 'Double Acting Hydraulic Cylinders',
        description: 'Versatile cylinders providing powered force in both extension and retraction strokes.',
        category: 'Hydraulic Cylinders',
        imageSrc: '/images/products/hydraulic-cylinders/double-acting-hydraulic-cylinders-manufacturer.webp',
        href: '/products/hydraulic-cylinders/double-acting-hydraulic-cylinders/',
        ctaText: 'View Details',
      },
      {
        title: 'Hydraulic Power Packs',
        description: 'Custom engineered power units to drive your parking system hydraulic cylinders.',
        category: 'Power Packs',
        imageSrc: '/images/products/hydraulic-power-packs/hydraulic-power-pack-manufacturer.webp',
        href: '/products/hydraulic-power-packs/',
        ctaText: 'View Details',
      },
    ],
  },

  // ── Local Service Areas ──
  productName: 'Car Parking Hydraulic Cylinders',

  // ── FAQs ──
  faqs: [
    {
      question: 'Which hydraulic cylinder is used in car parking systems?',
      answer: 'The most common type is a vertically mounted Single-Acting Displacement Cylinder. It uses hydraulic pressure to extend and lift the vehicle, and relies on gravity and the weight of the platform to safely retract and lower the vehicle. Telescopic cylinders are also used when pit space is limited.',
    },
    {
      question: 'How much load can a parking lift cylinder handle?',
      answer: 'Our standard car parking hydraulic cylinders are engineered to lift up to 3000 kg (3 Tonnes), which easily accommodates large SUVs and heavy commercial vehicles. We can also custom-manufacture higher capacity cylinders if required.',
    },
    {
      question: 'Is it suitable for outdoor parking environments?',
      answer: 'Yes. For outdoor parking systems, we manufacture cylinders with extra-thick hard chrome plating on the piston rod and utilize specialized weather-resistant wiper seals to protect the internal hydraulics from rain, dust, and temperature fluctuations.',
    },
    {
      question: 'What safety features prevent the car from falling?',
      answer: 'Safety is critical in vehicle lifting. Our cylinders are designed to accommodate velocity fuses (rupture valves) directly at the cylinder port. In the rare event of a hydraulic hose burst, this valve instantly locks the fluid inside the cylinder, freezing the platform in place and preventing a catastrophic drop.',
    },
    {
      question: 'Do you manufacture OEM cylinders for parking system companies?',
      answer: 'Yes, we are a leading OEM partner for parking system manufacturers across India. We can mass-produce cylinders customized to your exact stroke lengths, mounting configurations, and pressure ratings to integrate seamlessly into your proprietary parking lift designs.',
    },
  ],

  // ── Final CTA ──
  cta: {
    title: 'Require Reliable Cylinders for Your Parking Systems?',
    description: "Partner with Honeywell Hydraulics for OEM-grade, precision-engineered lifting cylinders built for high-cycle operations and absolute safety.",
    primaryCtaText: 'REQUEST OEM QUOTE',
    primaryCtaHref: '/request-quote/#quote-form',
    secondaryCtaText: 'Call Now',
    secondaryCtaHref: 'tel:+919924343873',
  },
};
