import React from 'react';
import {
  Shrink,
  Wrench,
  CircuitBoard,
  Droplets,
  Thermometer,
} from 'lucide-react';
import type { ManifoldSpec, ManifoldFeature, FAQ, ComparisonRow } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// Technical Specifications (from Section 8)
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTOM_SPECS: ManifoldSpec[] = [
  { parameter: 'Maximum Block Size', value: 'Up to 600mm × 400mm × 350mm (larger on request)' },
  { parameter: 'Material Options', value: 'AL 6061-T6, ST52 Carbon Steel, EN24T Alloy Steel, SS316' },
  { parameter: 'Max Working Pressure', value: 'Aluminum: 210 Bar. Steel: 315–500 Bar. EN24T: Up to 700 Bar' },
  { parameter: 'Valve Interfaces', value: 'CETOP 3/5/7/8, SAE, Sun/HydraForce cartridges, Proportional' },
  { parameter: 'Internal Gallery Finish', value: 'Burr-free, flushed, Ra 1.6 µm minimum' },
  { parameter: 'Port Thread Options', value: 'BSPP, NPT, SAE O-Ring Boss, SAE Code 61/62 Flange' },
  { parameter: 'Documentation', value: '3D STEP, PDF drawing, gallery schematic, hydrostatic test cert.' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Why Custom? (from Section 3)
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTOM_REASONS: ManifoldFeature[] = [
  {
    icon: React.createElement(Shrink, { className: 'w-5 h-5' }),
    title: 'Space is Critically Constrained',
    description: 'The machine frame cannot accommodate a standard multi-station block layout. A custom block is machined to the exact external dimensions that fit the available space.',
  },
  {
    icon: React.createElement(Wrench, { className: 'w-5 h-5' }),
    title: 'Cartridge Valves Are Required',
    description: 'Screw-in cartridge valves provide far superior logic density than CETOP valves. Integrating them requires custom cavities machined to proprietary specifications.',
  },
  {
    icon: React.createElement(CircuitBoard, { className: 'w-5 h-5' }),
    title: 'Circuit-Specific Logic',
    description: 'The system requires a unique internal port interconnection—for example, a cylinder that must regenerate its own return oil into the advance port.',
  },
  {
    icon: React.createElement(Droplets, { className: 'w-5 h-5' }),
    title: 'Leak Elimination is Paramount',
    description: 'In food processing, clean-room manufacturing, or precision test rigs, even a single external fitting is unacceptable. A monolithic block eliminates all external interconnections.',
  },
  {
    icon: React.createElement(Thermometer, { className: 'w-5 h-5' }),
    title: 'Thermal Management',
    description: 'We can machine integral cooling galleries inside the block body itself, circulating coolant water through the block to extract heat generated by high-flow proportional valves.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Custom vs Standard Comparison (from Section 5)
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTOM_VS_STANDARD: ComparisonRow[] = [
  { feature: 'Space Required', columns: ['Minimum (machined to fit exact cavity)', 'Fixed, often larger footprint'] },
  { feature: 'Valve Technology', columns: ['Any — CETOP, SAE, Cartridge, Proportional', 'Primarily CETOP directional valves'] },
  { feature: 'Logic Density', columns: ['Maximum (up to 20+ logic elements)', 'Medium (up to 8–10 valves)'] },
  { feature: 'External Fittings', columns: ['Zero. All logic is internal', 'Some external connectors required'] },
  { feature: 'Lead Time', columns: ['3–6 weeks (design + machining)', '1–2 weeks (machining only)'] },
  { feature: 'Unit Cost', columns: ['Higher (engineering + machining)', 'Lower'] },
  { feature: 'Best For', columns: ['Complex SPMs, test rigs, OEM production', 'General industrial automation'] },
];

// ─────────────────────────────────────────────────────────────────────────────
// Design Process (from Section 4)
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTOM_PROCESS = [
  {
    title: 'Circuit Analysis',
    description: 'We receive your hydraulic schematic (P&ID) and your machine\'s space constraints. Our engineers analyse every valve, every flow path, and every pressure requirement.',
  },
  {
    title: '3D Spatial Layout (CAD)',
    description: 'We model the complete manifold block in 3D CAD. We plan every internal gallery, checking for wall thickness compliance, intersection angles, and plug positions. Every gallery bore is sized for velocity below 6 m/s.',
  },
  {
    title: 'Client Review',
    description: 'We provide the complete 3D model and a detailed PDF layout drawing for your review. You verify port positions, mounting orientations, and access for wrench clearance before a single gram of metal is cut.',
  },
  {
    title: 'CNC Machining',
    description: 'Approved designs enter our CNC machining centre. Deep-hole drilling rigs execute the gallery bores. 5-axis machining centres cut the cartridge valve cavities to the valve manufacturer\'s exact specifications.',
  },
  {
    title: 'Hydrostatic Leak Testing',
    description: 'The completed block is sealed, connected to our test rig, and pressurized to 1.5x maximum working pressure. We verify zero internal cross-port leakage and zero external leakage.',
  },
  {
    title: 'Documentation',
    description: 'You receive a complete technical dossier: the 3D STEP CAD model, PDF manufacturing drawing, internal gallery schematic, bill of materials (valve cavities and plugs), and the hydrostatic test certificate.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FAQs
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTOM_FAQS: FAQ[] = [
  {
    question: 'What do I need to provide to get a custom manifold block designed?',
    answer: 'The minimum requirement is a hydraulic circuit schematic (P&ID) showing all valves, flow paths, and working pressures. Ideally, also provide the available space dimensions and the port connection orientations you require. Our team will handle all 3D spatial layout and gallery sizing calculations.',
  },
  {
    question: 'How long does the design and manufacturing process take?',
    answer: 'For a first-article prototype, allow 3–6 weeks from approved design to delivery. This includes 1–2 weeks for 3D CAD design and client review, plus 2–4 weeks for CNC machining, deburring, plating, and testing. Series production of approved designs follows a faster, repeat-run timeline.',
  },
  {
    question: 'Can you reverse-engineer a manifold block from an existing imported block that has failed?',
    answer: 'Yes. If you supply the failed block, we can measure all external dimensions, port positions, and identify the internal gallery logic by pressure-testing each port combination. We then design a fully documented local replacement block that may be improved upon the original.',
  },
  {
    question: 'What is the smallest custom manifold block you can manufacture?',
    answer: 'We have machined blocks as small as 60mm × 40mm × 50mm integrating 3 cartridge valve cavities. The practical minimum is governed by the wall thickness required between pressure galleries — minimum 8mm wall for aluminium at 210 Bar, 6mm wall for steel at 315 Bar.',
  },
];
